/**
 * VectraDB Explorer - Embed Data / Document Ingestion Page
 */

import { api } from "../api.js"
import { toast } from "../components/toast.js"
import { formatFloat, truncateText, escapeHtml } from "../utils/formatters.js"

const SAMPLE_DOCS = [
  {
    name: "React Architecture",
    id: "react-guide",
    source: "react-guide.txt",
    text: "React is a JavaScript library for building user interfaces. React applications are composed of reusable components. Components can manage their own state and receive data through props. Next.js is a React framework for production web applications. React hooks like useState and useEffect allow function components to handle stateful logic and side effects.",
  },
  {
    name: "Vector Databases & HNSW",
    id: "vector-search-guide",
    source: "vectordb-architecture.md",
    text: "Vector databases store high-dimensional embeddings generated by neural networks. Unlike traditional relational databases that perform exact keyword matches, vector databases find semantically similar items using Cosine Similarity or Euclidean distance. HNSW (Hierarchical Navigable Small World) structures vectors into multi-layer graph skip-lists, providing sub-millisecond approximate nearest neighbor retrieval.",
  },
  {
    name: "Transformer Embeddings",
    id: "transformer-models",
    source: "transformers-overview.txt",
    text: "Transformer models like multilingual-e5-small project arbitrary human language into dense 384-dimensional vector spaces. Sentences with similar semantic meanings map to vectors that are mathematically close to each other. Mean pooling and L2 unit normalization ensure that dot products directly correspond to cosine similarities.",
  },
]

export class EmbedPage {
  constructor(container) {
    this.container = container
    this.isIngesting = false
  }

  async render() {
    this.container.innerHTML = `
      <div class="page-container fade-in">
        <div class="page-header">
          <div>
            <h1 class="page-title">Embed & Ingest Document</h1>
            <p class="page-subtitle">Transform raw text into word-aware chunks, 384D transformer embeddings, and indexed HNSW nodes</p>
          </div>
        </div>

        <div class="embed-layout-grid">
          <!-- Ingestion Form -->
          <div class="card embed-form-card">
            <div class="card-header">
              <h3 class="card-title">Document Ingestion Pipeline</h3>
              <div class="sample-loader-group">
                <span class="sample-label">Load Preset:</span>
                ${SAMPLE_DOCS.map((doc, idx) => `
                  <button class="btn btn-xs btn-outline" data-sample-idx="${idx}">
                    ${doc.name}
                  </button>
                `).join("")}
              </div>
            </div>

            <form id="embed-doc-form" class="embed-form">
              <div class="form-row">
                <div class="form-group">
                  <label class="form-label" for="doc-id">Document ID <span class="required">*</span></label>
                  <input type="text" id="doc-id" class="form-input font-mono" placeholder="e.g. react-guide" required />
                  <span class="form-hint">Unique identifier for this document</span>
                </div>
                <div class="form-group">
                  <label class="form-label" for="doc-source">Source Name <span class="required">*</span></label>
                  <input type="text" id="doc-source" class="form-input font-mono" placeholder="e.g. react-guide.txt" required />
                  <span class="form-hint">Filename, URL or origin of content</span>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group">
                  <label class="form-label" for="chunk-size">Chunk Size (chars)</label>
                  <input type="number" id="chunk-size" class="form-input font-mono" value="500" min="50" max="4000" />
                  <span class="form-hint">Target characters per word-aware chunk</span>
                </div>
                <div class="form-group">
                  <label class="form-label" for="chunk-overlap">Chunk Overlap (chars)</label>
                  <input type="number" id="chunk-overlap" class="form-input font-mono" value="50" min="0" max="500" />
                  <span class="form-hint">Contextual overlap between consecutive chunks</span>
                </div>
              </div>

              <div class="form-group">
                <label class="form-label" for="doc-text">Document Text <span class="required">*</span></label>
                <textarea id="doc-text" class="form-textarea" rows="7" placeholder="Paste full article or text here..." required></textarea>
                <div class="char-counter"><span id="char-count">0</span> characters</div>
              </div>

              <div class="form-actions">
                <button type="submit" class="btn btn-primary btn-lg" id="btn-submit-embed">
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                  Embed Document
                </button>
                <button type="button" class="btn btn-secondary" id="btn-clear-form">Clear</button>
              </div>
            </form>
          </div>

          <!-- Live Step-by-Step Progress & Results -->
          <div class="card embed-progress-card">
            <div class="card-header">
              <h3 class="card-title">Live Pipeline Execution</h3>
              <span class="status-badge-live" id="pipeline-status-badge">Idle</span>
            </div>

            <!-- Visual Stage Flow Tracker -->
            <div class="step-tracker-container" id="step-tracker">
              <div class="step-item step-idle" id="step-1">
                <div class="step-circle"><span class="step-num">1</span></div>
                <div class="step-info">
                  <div class="step-title">Document Received</div>
                  <div class="step-sub">Validated ID & text payload</div>
                </div>
              </div>
              <div class="step-line" id="line-1"></div>

              <div class="step-item step-idle" id="step-2">
                <div class="step-circle"><span class="step-num">2</span></div>
                <div class="step-info">
                  <div class="step-title">Word-Aware Chunking</div>
                  <div class="step-sub">Sliced with boundary overlap</div>
                </div>
              </div>
              <div class="step-line" id="line-2"></div>

              <div class="step-item step-idle" id="step-3">
                <div class="step-circle"><span class="step-num">3</span></div>
                <div class="step-info">
                  <div class="step-title">Generating 384D Embeddings</div>
                  <div class="step-sub">Xenova/multilingual-e5-small</div>
                </div>
              </div>
              <div class="step-line" id="line-3"></div>

              <div class="step-item step-idle" id="step-4">
                <div class="step-circle"><span class="step-num">4</span></div>
                <div class="step-info">
                  <div class="step-title">Storing Vectors</div>
                  <div class="step-sub">In-Memory + data/vectors.json</div>
                </div>
              </div>
              <div class="step-line" id="line-4"></div>

              <div class="step-item step-idle" id="step-5">
                <div class="step-circle"><span class="step-num">5</span></div>
                <div class="step-info">
                  <div class="step-title">Building HNSW Index</div>
                  <div class="step-sub">Multi-layer neighbor pruning</div>
                </div>
              </div>
            </div>

            <!-- Ingestion Result Display -->
            <div class="embed-results-container hidden" id="embed-results-container"></div>
          </div>
        </div>
      </div>
    `

    this.setupEvents()
    // Pre-populate with sample 1
    this.loadSample(0)
  }

  setupEvents() {
    const form = this.container.querySelector("#embed-doc-form")
    const textarea = this.container.querySelector("#doc-text")
    const charCountEl = this.container.querySelector("#char-count")
    const clearBtn = this.container.querySelector("#btn-clear-form")

    textarea.addEventListener("input", () => {
      charCountEl.textContent = textarea.value.length
    })

    form.addEventListener("submit", (e) => {
      e.preventDefault()
      this.handleIngest()
    })

    clearBtn.addEventListener("click", () => {
      form.reset()
      charCountEl.textContent = "0"
      this.resetSteps()
      const resultsContainer = this.container.querySelector("#embed-results-container")
      resultsContainer.classList.add("hidden")
      resultsContainer.innerHTML = ""
    })

    // Preset buttons
    this.container.querySelectorAll("[data-sample-idx]").forEach((btn) => {
      btn.addEventListener("click", (e) => {
        e.preventDefault()
        const idx = Number(btn.getAttribute("data-sample-idx"))
        this.loadSample(idx)
      })
    })
  }

  loadSample(index) {
    const sample = SAMPLE_DOCS[index]
    if (!sample) return

    const docIdInput = this.container.querySelector("#doc-id")
    const sourceInput = this.container.querySelector("#doc-source")
    const textInput = this.container.querySelector("#doc-text")
    const charCountEl = this.container.querySelector("#char-count")

    docIdInput.value = sample.id
    sourceInput.value = sample.source
    textInput.value = sample.text
    charCountEl.textContent = sample.text.length
  }

  resetSteps() {
    for (let i = 1; i <= 5; i++) {
      const step = this.container.querySelector(`#step-${i}`)
      if (step) {
        step.className = "step-item step-idle"
      }
      const line = this.container.querySelector(`#line-${i}`)
      if (line) {
        line.className = "step-line"
      }
    }
    const badge = this.container.querySelector("#pipeline-status-badge")
    if (badge) {
      badge.textContent = "Idle"
      badge.className = "status-badge-live"
    }
  }

  setStepStatus(stepNum, status = "active") {
    const step = this.container.querySelector(`#step-${stepNum}`)
    if (step) {
      step.className = `step-item step-${status}`
    }
    if (stepNum > 1) {
      const line = this.container.querySelector(`#line-${stepNum - 1}`)
      if (line) {
        line.className = `step-line ${status === "done" ? "line-done" : ""}`
      }
    }
  }

  async handleIngest() {
    if (this.isIngesting) return

    const docId = this.container.querySelector("#doc-id").value.trim()
    const source = this.container.querySelector("#doc-source").value.trim()
    const text = this.container.querySelector("#doc-text").value.trim()

    if (!docId || !text) {
      toast.error("Document ID and Text are required")
      return
    }

    this.isIngesting = true
    const submitBtn = this.container.querySelector("#btn-submit-embed")
    submitBtn.disabled = true
    submitBtn.innerHTML = `<span class="spinner-sm"></span> Ingesting...`

    const badge = this.container.querySelector("#pipeline-status-badge")
    badge.textContent = "Processing Pipeline..."
    badge.className = "status-badge-live badge-running"

    this.resetSteps()

    try {
      // Step 1: Received
      this.setStepStatus(1, "active")
      await new Promise((r) => setTimeout(r, 200))
      this.setStepStatus(1, "done")

      // Step 2: Chunking
      this.setStepStatus(2, "active")
      await new Promise((r) => setTimeout(r, 250))
      this.setStepStatus(2, "done")

      // Step 3: Embeddings
      this.setStepStatus(3, "active")

      // Send to Backend API
      const response = await api.ingestDocument({
        documentId: docId,
        source: source || docId,
        text,
      })

      this.setStepStatus(3, "done")

      // Step 4: Storing
      this.setStepStatus(4, "active")
      await new Promise((r) => setTimeout(r, 150))
      this.setStepStatus(4, "done")

      // Step 5: HNSW Indexing
      this.setStepStatus(5, "active")
      await new Promise((r) => setTimeout(r, 150))
      this.setStepStatus(5, "done")

      badge.textContent = "Completed Successfully ✓"
      badge.className = "status-badge-live badge-success"

      toast.success(`Document "${docId}" ingested (${response.data?.chunkCount || 1} chunks created)`)

      this.renderResults(response.data)
    } catch (err) {
      badge.textContent = "Ingestion Failed ✕"
      badge.className = "status-badge-live badge-error"
      toast.error(`Ingestion error: ${err.message}`)
    } finally {
      this.isIngesting = false
      submitBtn.disabled = false
      submitBtn.innerHTML = `
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
        Embed Document
      `
    }
  }

  renderResults(data) {
    const resultsContainer = this.container.querySelector("#embed-results-container")
    if (!resultsContainer || !data) return

    const chunks = data.chunks || []

    resultsContainer.innerHTML = `
      <div class="embed-success-summary">
        <div class="summary-header">
          <div class="summary-icon">✓</div>
          <div>
            <h4 class="summary-title">Document Embedded & Indexed</h4>
            <div class="summary-meta font-mono">
              <span><strong>Doc ID:</strong> ${escapeHtml(data.documentId)}</span>
              <span><strong>Source:</strong> ${escapeHtml(data.source)}</span>
              <span><strong>Chunks:</strong> ${data.chunkCount}</span>
              <span><strong>Dimension:</strong> 384D</span>
            </div>
          </div>
        </div>

        ${
          chunks.length > 0
            ? `
          <div class="chunks-section">
            <h5 class="chunks-heading">Generated Chunks (${chunks.length})</h5>
            <div class="chunks-list">
              ${chunks
                .map(
                  (chunk, idx) => `
                <div class="chunk-item-card">
                  <div class="chunk-card-header">
                    <span class="chunk-idx-badge">Chunk #${chunk.metadata?.chunkIndex !== undefined ? chunk.metadata.chunkIndex : idx}</span>
                    <span class="chunk-id-tag font-mono">${escapeHtml(chunk.id || `${data.documentId}-chunk-${idx}`)}</span>
                    <span class="chunk-dim-badge">384 Dimensions</span>
                  </div>
                  <div class="chunk-text-body">"${escapeHtml(chunk.metadata?.text || chunk.text || "")}"</div>
                  <div class="chunk-card-footer">
                    <span class="font-mono text-muted">Doc: ${escapeHtml(data.documentId)} | Source: ${escapeHtml(data.source)}</span>
                  </div>
                </div>
              `,
                )
                .join("")}
            </div>
          </div>
        `
            : ""
        }
      </div>
    `

    resultsContainer.classList.remove("hidden")
  }
}
